<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-13 12:32:04.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Alumno
 *
 * @ORM\Entity(repositoryClass="Umg\VotacionBundle\Entity\AlumnoRepository")
 * @ORM\Table(name="Alumno", indexes={@ORM\Index(name="fk_Alumno_Usuario1_idx", columns={"Usuario_id"})})
 */
class Alumno
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="string", length=45)
     */
    protected $Carne;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Usuario_id;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoCurso", mappedBy="alumno")
     * @ORM\JoinColumn(name="id", referencedColumnName="Alumno_id")
     */
    protected $alumnoCursos;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="alumnos")
     * @ORM\JoinColumn(name="Usuario_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario;

    public function __construct()
    {
        $this->alumnoCursos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Carne.
     *
     * @param string $Carne
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function setCarne($Carne)
    {
        $this->Carne = $Carne;

        return $this;
    }

    /**
     * Get the value of Carne.
     *
     * @return string
     */
    public function getCarne()
    {
        return $this->Carne;
    }

    /**
     * Set the value of Usuario_id.
     *
     * @param integer $Usuario_id
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function setUsuarioId($Usuario_id)
    {
        $this->Usuario_id = $Usuario_id;

        return $this;
    }

    /**
     * Get the value of Usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->Usuario_id;
    }

    /**
     * Add AlumnoCurso entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\AlumnoCurso $alumnoCurso
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function addAlumnoCurso(AlumnoCurso $alumnoCurso)
    {
        $this->alumnoCursos[] = $alumnoCurso;

        return $this;
    }

    /**
     * Remove AlumnoCurso entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\AlumnoCurso $alumnoCurso
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function removeAlumnoCurso(AlumnoCurso $alumnoCurso)
    {
        $this->alumnoCursos->removeElement($alumnoCurso);

        return $this;
    }

    /**
     * Get AlumnoCurso entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoCursos()
    {
        return $this->alumnoCursos;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Usuario $usuario
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Carne', 'Usuario_id');
    }
    
    public function __toString() {
        return $this->Carne.' - '.$this->Nombre;
    }
}
