<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-03-23 20:21:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\AlumnoCurso
 *
 * @ORM\Entity()
 * @ORM\Table(name="AlumnoCurso", indexes={@ORM\Index(name="fk_AlumnoCurso_Alumno1_idx", columns={"Alumno_id"}), @ORM\Index(name="fk_AlumnoCurso_CatedraticoCurso1_idx", columns={"CatedraticoCurso_id"})})
 */
class AlumnoCurso
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Alumno_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $CatedraticoCurso_id;

    /**
     * @ORM\OneToMany(targetEntity="Respuestum", mappedBy="alumnoCurso")
     * @ORM\JoinColumn(name="id", referencedColumnName="AlumnoCurso_id")
     */
    protected $respuesta;

    /**
     * @ORM\ManyToOne(targetEntity="Alumno", inversedBy="alumnoCursos")
     * @ORM\JoinColumn(name="Alumno_id", referencedColumnName="id")
     */
    protected $alumno;

    /**
     * @ORM\ManyToOne(targetEntity="CatedraticoCurso", inversedBy="alumnoCursos")
     * @ORM\JoinColumn(name="CatedraticoCurso_id", referencedColumnName="id")
     */
    protected $catedraticoCurso;

    public function __construct()
    {
        $this->respuesta = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Alumno_id.
     *
     * @param integer $Alumno_id
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setAlumnoId($Alumno_id)
    {
        $this->Alumno_id = $Alumno_id;

        return $this;
    }

    /**
     * Get the value of Alumno_id.
     *
     * @return integer
     */
    public function getAlumnoId()
    {
        return $this->Alumno_id;
    }

    /**
     * Set the value of CatedraticoCurso_id.
     *
     * @param integer $CatedraticoCurso_id
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setCatedraticoCursoId($CatedraticoCurso_id)
    {
        $this->CatedraticoCurso_id = $CatedraticoCurso_id;

        return $this;
    }

    /**
     * Get the value of CatedraticoCurso_id.
     *
     * @return integer
     */
    public function getCatedraticoCursoId()
    {
        return $this->CatedraticoCurso_id;
    }

    /**
     * Add Respuestum entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Respuestum $respuestum
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function addRespuestum(Respuestum $respuestum)
    {
        $this->respuesta[] = $respuestum;

        return $this;
    }

    /**
     * Remove Respuestum entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Respuestum $respuestum
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function removeRespuestum(Respuestum $respuestum)
    {
        $this->respuesta->removeElement($respuestum);

        return $this;
    }

    /**
     * Get Respuestum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRespuesta()
    {
        return $this->respuesta;
    }

    /**
     * Set Alumno entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Alumno $alumno
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setAlumno(Alumno $alumno = null)
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * Get Alumno entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function getAlumno()
    {
        return $this->alumno;
    }

    /**
     * Set CatedraticoCurso entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\CatedraticoCurso $catedraticoCurso
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setCatedraticoCurso(CatedraticoCurso $catedraticoCurso = null)
    {
        $this->catedraticoCurso = $catedraticoCurso;

        return $this;
    }

    /**
     * Get CatedraticoCurso entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\CatedraticoCurso
     */
    public function getCatedraticoCurso()
    {
        return $this->catedraticoCurso;
    }

    public function __sleep()
    {
        return array('id', 'Alumno_id', 'CatedraticoCurso_id');
    }
}