<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-12 18:04:42.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\AlumnoCurso
 *
 * @ORM\Entity()
 * @ORM\Table(name="AlumnoCurso", indexes={@ORM\Index(name="fk_AlumnoCurso_Alumno1_idx", columns={"Alumno_id"}), @ORM\Index(name="fk_AlumnoCurso_CarreraCurso1_idx", columns={"CarreraCurso_id"})})
 */
class AlumnoCurso
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Alumno_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $CarreraCurso_id;

    /**
     * @ORM\OneToMany(targetEntity="Respuestum", mappedBy="alumnoCurso")
     * @ORM\JoinColumn(name="id", referencedColumnName="AlumnoCurso_id")
     */
    protected $respuesta;

    /**
     * @ORM\ManyToOne(targetEntity="Alumno", inversedBy="alumnoCursos")
     * @ORM\JoinColumn(name="Alumno_id", referencedColumnName="id")
     */
    protected $alumno;

    /**
     * @ORM\ManyToOne(targetEntity="CarreraCurso", inversedBy="alumnoCursos")
     * @ORM\JoinColumn(name="CarreraCurso_id", referencedColumnName="id")
     */
    protected $carreraCurso;

    public function __construct()
    {
        $this->respuesta = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Alumno_id.
     *
     * @param integer $Alumno_id
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setAlumnoId($Alumno_id)
    {
        $this->Alumno_id = $Alumno_id;

        return $this;
    }

    /**
     * Get the value of Alumno_id.
     *
     * @return integer
     */
    public function getAlumnoId()
    {
        return $this->Alumno_id;
    }

    /**
     * Set the value of CarreraCurso_id.
     *
     * @param integer $CarreraCurso_id
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setCarreraCursoId($CarreraCurso_id)
    {
        $this->CarreraCurso_id = $CarreraCurso_id;

        return $this;
    }

    /**
     * Get the value of CarreraCurso_id.
     *
     * @return integer
     */
    public function getCarreraCursoId()
    {
        return $this->CarreraCurso_id;
    }

    /**
     * Add Respuestum entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Respuestum $respuestum
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function addRespuestum(Respuestum $respuestum)
    {
        $this->respuesta[] = $respuestum;

        return $this;
    }

    /**
     * Remove Respuestum entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Respuestum $respuestum
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function removeRespuestum(Respuestum $respuestum)
    {
        $this->respuesta->removeElement($respuestum);

        return $this;
    }

    /**
     * Get Respuestum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRespuesta()
    {
        return $this->respuesta;
    }

    /**
     * Set Alumno entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Alumno $alumno
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setAlumno(Alumno $alumno = null)
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * Get Alumno entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Alumno
     */
    public function getAlumno()
    {
        return $this->alumno;
    }

    /**
     * Set CarreraCurso entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\CarreraCurso $carreraCurso
     * @return \Umg\VotacionBundle\Entity\AlumnoCurso
     */
    public function setCarreraCurso(CarreraCurso $carreraCurso = null)
    {
        $this->carreraCurso = $carreraCurso;

        return $this;
    }

    /**
     * Get CarreraCurso entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function getCarreraCurso()
    {
        return $this->carreraCurso;
    }

    public function __sleep()
    {
        return array('id', 'Alumno_id', 'CarreraCurso_id');
    }
}