<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-11 12:20:51.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Carrera
 *
 * @ORM\Entity()
 * @ORM\Table(name="Carrera")
 */
class Carrera
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $Carrera;

    /**
     * @ORM\OneToMany(targetEntity="CampusCarrera", mappedBy="carrera")
     * @ORM\JoinColumn(name="id", referencedColumnName="Carrera_id")
     */
    protected $campusCarreras;

    /**
     * @ORM\OneToMany(targetEntity="PensumAnio", mappedBy="carrera")
     * @ORM\JoinColumn(name="id", referencedColumnName="Carrera_id")
     */
    protected $pensumAnios;

    public function __construct()
    {
        $this->campusCarreras = new ArrayCollection();
        $this->pensumAnios = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Carrera
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Carrera.
     *
     * @param string $Carrera
     * @return \Umg\VotacionBundle\Entity\Carrera
     */
    public function setCarrera($Carrera)
    {
        $this->Carrera = $Carrera;

        return $this;
    }

    /**
     * Get the value of Carrera.
     *
     * @return string
     */
    public function getCarrera()
    {
        return $this->Carrera;
    }

    /**
     * Add CampusCarrera entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\Carrera
     */
    public function addCampusCarrera(CampusCarrera $campusCarrera)
    {
        $this->campusCarreras[] = $campusCarrera;

        return $this;
    }

    /**
     * Remove CampusCarrera entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\Carrera
     */
    public function removeCampusCarrera(CampusCarrera $campusCarrera)
    {
        $this->campusCarreras->removeElement($campusCarrera);

        return $this;
    }

    /**
     * Get CampusCarrera entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCampusCarreras()
    {
        return $this->campusCarreras;
    }

    /**
     * Add PensumAnio entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\PensumAnio $pensumAnio
     * @return \Umg\VotacionBundle\Entity\Carrera
     */
    public function addPensumAnio(PensumAnio $pensumAnio)
    {
        $this->pensumAnios[] = $pensumAnio;

        return $this;
    }

    /**
     * Remove PensumAnio entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\PensumAnio $pensumAnio
     * @return \Umg\VotacionBundle\Entity\Carrera
     */
    public function removePensumAnio(PensumAnio $pensumAnio)
    {
        $this->pensumAnios->removeElement($pensumAnio);

        return $this;
    }

    /**
     * Get PensumAnio entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPensumAnios()
    {
        return $this->pensumAnios;
    }

    public function __sleep()
    {
        return array('id', 'Carrera');
    }
    
    public function __toString() {
        return $this->Carrera;
    }
}