<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-12 18:04:42.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\CarreraCurso
 *
 * @ORM\Entity(repositoryClass="Umg\VotacionBundle\Entity\CarreraCursoRepository")
 * @ORM\Table(name="CarreraCurso", indexes={@ORM\Index(name="fk_CarreraCurso_CampusCarrera1_idx", columns={"CampusCarrera_id"}), @ORM\Index(name="fk_CarreraCurso_PensumAnio1_idx", columns={"PensumAnio_id"})})
 */
class CarreraCurso
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $CampusCarrera_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $PensumAnio_id;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoCurso", mappedBy="carreraCurso")
     * @ORM\JoinColumn(name="id", referencedColumnName="CarreraCurso_id")
     */
    protected $alumnoCursos;

    /**
     * @ORM\OneToMany(targetEntity="CatedraticoCurso", mappedBy="carreraCurso")
     * @ORM\JoinColumn(name="id", referencedColumnName="CampusCurso_id")
     */
    protected $catedraticoCursos;

    /**
     * @ORM\ManyToOne(targetEntity="CampusCarrera", inversedBy="carreraCursos")
     * @ORM\JoinColumn(name="CampusCarrera_id", referencedColumnName="id")
     */
    protected $campusCarrera;

    /**
     * @ORM\ManyToOne(targetEntity="PensumAnio", inversedBy="carreraCursos")
     * @ORM\JoinColumn(name="PensumAnio_id", referencedColumnName="id")
     */
    protected $pensumAnio;

    public function __construct()
    {
        $this->alumnoCursos = new ArrayCollection();
        $this->catedraticoCursos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of CampusCarrera_id.
     *
     * @param integer $CampusCarrera_id
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function setCampusCarreraId($CampusCarrera_id)
    {
        $this->CampusCarrera_id = $CampusCarrera_id;

        return $this;
    }

    /**
     * Get the value of CampusCarrera_id.
     *
     * @return integer
     */
    public function getCampusCarreraId()
    {
        return $this->CampusCarrera_id;
    }

    /**
     * Set the value of PensumAnio_id.
     *
     * @param integer $PensumAnio_id
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function setPensumAnioId($PensumAnio_id)
    {
        $this->PensumAnio_id = $PensumAnio_id;

        return $this;
    }

    /**
     * Get the value of PensumAnio_id.
     *
     * @return integer
     */
    public function getPensumAnioId()
    {
        return $this->PensumAnio_id;
    }

    /**
     * Add AlumnoCurso entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\AlumnoCurso $alumnoCurso
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function addAlumnoCurso(AlumnoCurso $alumnoCurso)
    {
        $this->alumnoCursos[] = $alumnoCurso;

        return $this;
    }

    /**
     * Remove AlumnoCurso entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\AlumnoCurso $alumnoCurso
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function removeAlumnoCurso(AlumnoCurso $alumnoCurso)
    {
        $this->alumnoCursos->removeElement($alumnoCurso);

        return $this;
    }

    /**
     * Get AlumnoCurso entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoCursos()
    {
        return $this->alumnoCursos;
    }

    /**
     * Add CatedraticoCurso entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CatedraticoCurso $catedraticoCurso
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function addCatedraticoCurso(CatedraticoCurso $catedraticoCurso)
    {
        $this->catedraticoCursos[] = $catedraticoCurso;

        return $this;
    }

    /**
     * Remove CatedraticoCurso entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CatedraticoCurso $catedraticoCurso
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function removeCatedraticoCurso(CatedraticoCurso $catedraticoCurso)
    {
        $this->catedraticoCursos->removeElement($catedraticoCurso);

        return $this;
    }

    /**
     * Get CatedraticoCurso entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCatedraticoCursos()
    {
        return $this->catedraticoCursos;
    }

    /**
     * Set CampusCarrera entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function setCampusCarrera(CampusCarrera $campusCarrera = null)
    {
        $this->campusCarrera = $campusCarrera;

        return $this;
    }

    /**
     * Get CampusCarrera entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\CampusCarrera
     */
    public function getCampusCarrera()
    {
        return $this->campusCarrera;
    }

    /**
     * Set PensumAnio entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\PensumAnio $pensumAnio
     * @return \Umg\VotacionBundle\Entity\CarreraCurso
     */
    public function setPensumAnio(PensumAnio $pensumAnio = null)
    {
        $this->pensumAnio = $pensumAnio;

        return $this;
    }

    /**
     * Get PensumAnio entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\PensumAnio
     */
    public function getPensumAnio()
    {
        return $this->pensumAnio;
    }

    public function __sleep()
    {
        return array('id', 'CampusCarrera_id', 'PensumAnio_id');
    }
    
    public function __toString() {
        #return $this->campusCarrera.', '.$this->pensumAnio;
        return $this->pensumAnio.', '.$this->campusCarrera;
    }
}
