<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-03-23 20:21:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Catedratico
 *
 * @ORM\Entity()
 * @ORM\Table(name="Catedratico")
 */
class Catedratico
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\OneToMany(targetEntity="CatedraticoCurso", mappedBy="catedratico")
     * @ORM\JoinColumn(name="id", referencedColumnName="Catedratico_id")
     */
    protected $catedraticoCursos;

    /**
     * @ORM\OneToMany(targetEntity="Respuestum", mappedBy="catedratico")
     * @ORM\JoinColumn(name="id", referencedColumnName="Catedratico_id")
     */
    protected $respuesta;

    public function __construct()
    {
        $this->catedraticoCursos = new ArrayCollection();
        $this->respuesta = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Catedratico
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\VotacionBundle\Entity\Catedratico
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Add CatedraticoCurso entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CatedraticoCurso $catedraticoCurso
     * @return \Umg\VotacionBundle\Entity\Catedratico
     */
    public function addCatedraticoCurso(CatedraticoCurso $catedraticoCurso)
    {
        $this->catedraticoCursos[] = $catedraticoCurso;

        return $this;
    }

    /**
     * Remove CatedraticoCurso entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CatedraticoCurso $catedraticoCurso
     * @return \Umg\VotacionBundle\Entity\Catedratico
     */
    public function removeCatedraticoCurso(CatedraticoCurso $catedraticoCurso)
    {
        $this->catedraticoCursos->removeElement($catedraticoCurso);

        return $this;
    }

    /**
     * Get CatedraticoCurso entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCatedraticoCursos()
    {
        return $this->catedraticoCursos;
    }

    /**
     * Add Respuestum entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Respuestum $respuestum
     * @return \Umg\VotacionBundle\Entity\Catedratico
     */
    public function addRespuestum(Respuestum $respuestum)
    {
        $this->respuesta[] = $respuestum;

        return $this;
    }

    /**
     * Remove Respuestum entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Respuestum $respuestum
     * @return \Umg\VotacionBundle\Entity\Catedratico
     */
    public function removeRespuestum(Respuestum $respuestum)
    {
        $this->respuesta->removeElement($respuestum);

        return $this;
    }

    /**
     * Get Respuestum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRespuesta()
    {
        return $this->respuesta;
    }

    public function __sleep()
    {
        return array('id', 'Nombre');
    }
    
    public function __toString() {
        return $this->Nombre;
    }
}