<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-03-23 20:21:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Evaluacion
 *
 * @ORM\Entity()
 * @ORM\Table(name="Evaluacion", indexes={@ORM\Index(name="fk_Evaluacion_CampusCarrera1_idx", columns={"CampusCarrera_id"})})
 */
class Evaluacion
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $Activa;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $FechaHora;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $FechaHoraFinal;

    /**
     * @ORM\Column(type="integer")
     */
    protected $CampusCarrera_id;

    /**
     * @ORM\OneToMany(targetEntity="Preguntum", mappedBy="evaluacion")
     * @ORM\JoinColumn(name="id", referencedColumnName="Evaluacion_id")
     */
    protected $pregunta;

    /**
     * @ORM\ManyToOne(targetEntity="CampusCarrera", inversedBy="evaluacions")
     * @ORM\JoinColumn(name="CampusCarrera_id", referencedColumnName="id")
     */
    protected $campusCarrera;

    public function __construct()
    {
        $this->pregunta = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Activa.
     *
     * @param boolean $Activa
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function setActiva($Activa)
    {
        $this->Activa = $Activa;

        return $this;
    }

    /**
     * Get the value of Activa.
     *
     * @return boolean
     */
    public function getActiva()
    {
        return $this->Activa;
    }

    /**
     * Set the value of FechaHora.
     *
     * @param datetime $FechaHora
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function setFechaHora($FechaHora)
    {
        $this->FechaHora = $FechaHora;

        return $this;
    }

    /**
     * Get the value of FechaHora.
     *
     * @return datetime
     */
    public function getFechaHora()
    {
        return $this->FechaHora;
    }

    /**
     * Set the value of FechaHoraFinal.
     *
     * @param datetime $FechaHoraFinal
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function setFechaHoraFinal($FechaHoraFinal)
    {
        $this->FechaHoraFinal = $FechaHoraFinal;

        return $this;
    }

    /**
     * Get the value of FechaHoraFinal.
     *
     * @return datetime
     */
    public function getFechaHoraFinal()
    {
        return $this->FechaHoraFinal;
    }

    /**
     * Set the value of CampusCarrera_id.
     *
     * @param integer $CampusCarrera_id
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function setCampusCarreraId($CampusCarrera_id)
    {
        $this->CampusCarrera_id = $CampusCarrera_id;

        return $this;
    }

    /**
     * Get the value of CampusCarrera_id.
     *
     * @return integer
     */
    public function getCampusCarreraId()
    {
        return $this->CampusCarrera_id;
    }

    /**
     * Add Preguntum entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Preguntum $preguntum
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function addPreguntum(Preguntum $preguntum)
    {
        $this->pregunta[] = $preguntum;

        return $this;
    }

    /**
     * Remove Preguntum entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Preguntum $preguntum
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function removePreguntum(Preguntum $preguntum)
    {
        $this->pregunta->removeElement($preguntum);

        return $this;
    }

    /**
     * Get Preguntum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPregunta()
    {
        return $this->pregunta;
    }

    /**
     * Set CampusCarrera entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\Evaluacion
     */
    public function setCampusCarrera(CampusCarrera $campusCarrera = null)
    {
        $this->campusCarrera = $campusCarrera;

        return $this;
    }

    /**
     * Get CampusCarrera entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\CampusCarrera
     */
    public function getCampusCarrera()
    {
        return $this->campusCarrera;
    }

    public function __sleep()
    {
        return array('id', 'Activa', 'FechaHora', 'FechaHoraFinal', 'CampusCarrera_id');
    }
    
    public function __toString() {
        
        return $this->campusCarrera.' '.$this->FechaHora->format('Y-m-d');
    }
}
