<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-03-23 20:21:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Jornada
 *
 * @ORM\Entity()
 * @ORM\Table(name="Jornada")
 */
class Jornada
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    protected $Jornada;

    /**
     * @ORM\OneToMany(targetEntity="CampusCarrera", mappedBy="jornada")
     * @ORM\JoinColumn(name="id", referencedColumnName="Jornada_id")
     */
    protected $campusCarreras;

    public function __construct()
    {
        $this->campusCarreras = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Jornada
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Jornada.
     *
     * @param string $Jornada
     * @return \Umg\VotacionBundle\Entity\Jornada
     */
    public function setJornada($Jornada)
    {
        $this->Jornada = $Jornada;

        return $this;
    }

    /**
     * Get the value of Jornada.
     *
     * @return string
     */
    public function getJornada()
    {
        return $this->Jornada;
    }

    /**
     * Add CampusCarrera entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\Jornada
     */
    public function addCampusCarrera(CampusCarrera $campusCarrera)
    {
        $this->campusCarreras[] = $campusCarrera;

        return $this;
    }

    /**
     * Remove CampusCarrera entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\CampusCarrera $campusCarrera
     * @return \Umg\VotacionBundle\Entity\Jornada
     */
    public function removeCampusCarrera(CampusCarrera $campusCarrera)
    {
        $this->campusCarreras->removeElement($campusCarrera);

        return $this;
    }

    /**
     * Get CampusCarrera entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCampusCarreras()
    {
        return $this->campusCarreras;
    }

    public function __sleep()
    {
        return array('id', 'Jornada');
    }
    
    public function __toString() {
        return $this->Jornada;
    }
}