<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-13 18:12:44.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\VotacionBundle\Entity\OpcionPreguntum
 *
 * @ORM\Entity()
 * @ORM\Table(name="OpcionPregunta", indexes={@ORM\Index(name="fk_OpcionPregunta_Opcion1_idx", columns={"Opcion_id"}), @ORM\Index(name="fk_OpcionPregunta_Pregunta1_idx", columns={"Pregunta_id"})})
 */
class OpcionPreguntum
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Opcion_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Pregunta_id;

    /**
     * @ORM\ManyToOne(targetEntity="Opcion", inversedBy="opcionPregunta")
     * @ORM\JoinColumn(name="Opcion_id", referencedColumnName="id")
     */
    protected $opcion;

    /**
     * @ORM\ManyToOne(targetEntity="Preguntum", inversedBy="opcionPregunta")
     * @ORM\JoinColumn(name="Pregunta_id", referencedColumnName="id")
     */
    protected $preguntum;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Opcion_id.
     *
     * @param integer $Opcion_id
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setOpcionId($Opcion_id)
    {
        $this->Opcion_id = $Opcion_id;

        return $this;
    }

    /**
     * Get the value of Opcion_id.
     *
     * @return integer
     */
    public function getOpcionId()
    {
        return $this->Opcion_id;
    }

    /**
     * Set the value of Pregunta_id.
     *
     * @param integer $Pregunta_id
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setPreguntaId($Pregunta_id)
    {
        $this->Pregunta_id = $Pregunta_id;

        return $this;
    }

    /**
     * Get the value of Pregunta_id.
     *
     * @return integer
     */
    public function getPreguntaId()
    {
        return $this->Pregunta_id;
    }

    /**
     * Set Opcion entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Opcion $opcion
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setOpcion(Opcion $opcion = null)
    {
        $this->opcion = $opcion;

        return $this;
    }

    /**
     * Get Opcion entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function getOpcion()
    {
        return $this->opcion;
    }

    /**
     * Set Preguntum entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Preguntum $preguntum
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setPreguntum(Preguntum $preguntum = null)
    {
        $this->preguntum = $preguntum;

        return $this;
    }

    /**
     * Get Preguntum entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Preguntum
     */
    public function getPreguntum()
    {
        return $this->preguntum;
    }

    public function __sleep()
    {
        return array('id', 'Opcion_id', 'Pregunta_id');
    }
}