<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-20 17:39:41.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\Opcion
 *
 * @ORM\Entity()
 * @ORM\Table(name="Opcion")
 */
class Opcion
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    protected $Opcion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Punteo;

    /**
     * @ORM\OneToMany(targetEntity="OpcionPreguntum", mappedBy="opcion")
     * @ORM\JoinColumn(name="id", referencedColumnName="Opcion_id")
     */
    protected $opcionPregunta;

    public function __construct()
    {
        $this->opcionPregunta = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Opcion.
     *
     * @param string $Opcion
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function setOpcion($Opcion)
    {
        $this->Opcion = $Opcion;

        return $this;
    }

    /**
     * Get the value of Opcion.
     *
     * @return string
     */
    public function getOpcion()
    {
        return $this->Opcion;
    }

    /**
     * Set the value of Punteo.
     *
     * @param integer $Punteo
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function setPunteo($Punteo)
    {
        $this->Punteo = $Punteo;

        return $this;
    }

    /**
     * Get the value of Punteo.
     *
     * @return integer
     */
    public function getPunteo()
    {
        return $this->Punteo;
    }

    /**
     * Add OpcionPreguntum entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\OpcionPreguntum $opcionPreguntum
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function addOpcionPreguntum(OpcionPreguntum $opcionPreguntum)
    {
        $this->opcionPregunta[] = $opcionPreguntum;

        return $this;
    }

    /**
     * Remove OpcionPreguntum entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\OpcionPreguntum $opcionPreguntum
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function removeOpcionPreguntum(OpcionPreguntum $opcionPreguntum)
    {
        $this->opcionPregunta->removeElement($opcionPreguntum);

        return $this;
    }

    /**
     * Get OpcionPreguntum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOpcionPregunta()
    {
        return $this->opcionPregunta;
    }

    public function __sleep()
    {
        return array('id', 'Opcion', 'Punteo');
    }

    public function __toString()
    {
        return $this->Opcion.' - '.$this->Punteo;
    }
}
