<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-03-23 20:21:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\VotacionBundle\Entity\OpcionPreguntum
 *
 * @ORM\Entity()
 * @ORM\Table(name="OpcionPregunta", indexes={@ORM\Index(name="fk_OpcionPregunta_TipoPregunta1_idx", columns={"TipoPregunta_id"}), @ORM\Index(name="fk_OpcionPregunta_Opcion1_idx", columns={"Opcion_id"})})
 */
class OpcionPreguntum
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $TipoPregunta_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Opcion_id;

    /**
     * @ORM\ManyToOne(targetEntity="TipoPreguntum", inversedBy="opcionPregunta")
     * @ORM\JoinColumn(name="TipoPregunta_id", referencedColumnName="id")
     */
    protected $tipoPreguntum;

    /**
     * @ORM\ManyToOne(targetEntity="Opcion", inversedBy="opcionPregunta")
     * @ORM\JoinColumn(name="Opcion_id", referencedColumnName="id")
     */
    protected $opcion;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of TipoPregunta_id.
     *
     * @param integer $TipoPregunta_id
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setTipoPreguntaId($TipoPregunta_id)
    {
        $this->TipoPregunta_id = $TipoPregunta_id;

        return $this;
    }

    /**
     * Get the value of TipoPregunta_id.
     *
     * @return integer
     */
    public function getTipoPreguntaId()
    {
        return $this->TipoPregunta_id;
    }

    /**
     * Set the value of Opcion_id.
     *
     * @param integer $Opcion_id
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setOpcionId($Opcion_id)
    {
        $this->Opcion_id = $Opcion_id;

        return $this;
    }

    /**
     * Get the value of Opcion_id.
     *
     * @return integer
     */
    public function getOpcionId()
    {
        return $this->Opcion_id;
    }

    /**
     * Set TipoPreguntum entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\TipoPreguntum $tipoPreguntum
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setTipoPreguntum(TipoPreguntum $tipoPreguntum = null)
    {
        $this->tipoPreguntum = $tipoPreguntum;

        return $this;
    }

    /**
     * Get TipoPreguntum entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\TipoPreguntum
     */
    public function getTipoPreguntum()
    {
        return $this->tipoPreguntum;
    }

    /**
     * Set Opcion entity (many to one).
     *
     * @param \Umg\VotacionBundle\Entity\Opcion $opcion
     * @return \Umg\VotacionBundle\Entity\OpcionPreguntum
     */
    public function setOpcion(Opcion $opcion = null)
    {
        $this->opcion = $opcion;

        return $this;
    }

    /**
     * Get Opcion entity (many to one).
     *
     * @return \Umg\VotacionBundle\Entity\Opcion
     */
    public function getOpcion()
    {
        return $this->opcion;
    }

    public function __sleep()
    {
        return array('id', 'TipoPregunta_id', 'Opcion_id');
    }
}