<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-13 18:12:44.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\VotacionBundle\Entity\TipoPreguntum
 *
 * @ORM\Entity()
 * @ORM\Table(name="TipoPregunta")
 */
class TipoPreguntum
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    protected $Tipo;

    /**
     * @ORM\OneToMany(targetEntity="Preguntum", mappedBy="tipoPreguntum")
     * @ORM\JoinColumn(name="id", referencedColumnName="TipoPregunta_id")
     */
    protected $pregunta;

    public function __construct()
    {
        $this->pregunta = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\VotacionBundle\Entity\TipoPreguntum
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Tipo.
     *
     * @param string $Tipo
     * @return \Umg\VotacionBundle\Entity\TipoPreguntum
     */
    public function setTipo($Tipo)
    {
        $this->Tipo = $Tipo;

        return $this;
    }

    /**
     * Get the value of Tipo.
     *
     * @return string
     */
    public function getTipo()
    {
        return $this->Tipo;
    }

    /**
     * Add Preguntum entity to collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Preguntum $preguntum
     * @return \Umg\VotacionBundle\Entity\TipoPreguntum
     */
    public function addPreguntum(Preguntum $preguntum)
    {
        $this->pregunta[] = $preguntum;

        return $this;
    }

    /**
     * Remove Preguntum entity from collection (one to many).
     *
     * @param \Umg\VotacionBundle\Entity\Preguntum $preguntum
     * @return \Umg\VotacionBundle\Entity\TipoPreguntum
     */
    public function removePreguntum(Preguntum $preguntum)
    {
        $this->pregunta->removeElement($preguntum);

        return $this;
    }

    /**
     * Get Preguntum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPregunta()
    {
        return $this->pregunta;
    }

    public function __sleep()
    {
        return array('id', 'Tipo');
    }
    
    public function __toString() {
        return $this->Tipo;
    }
}